version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile.prod
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - '4000:4000'
    env_file:
      - ./backend/.env.production
    volumes:
      - ./backend:/backend
      - /backend/node_modules

  admin:
    build:
      dockerfile: Dockerfile.prod
      context: ./admin
    container_name: admin
    ports:
      - '3001:3001'
      - '443:443'
    env_file:
      - ./admin/.env.production
    volumes:
      - ./admin:/admin
      - /admin/node_modules
    depends_on:
      - backend

  client:
    build:
      dockerfile: Dockerfile.prod
      context: ./client
    container_name: client
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - ./client/.env.production
    volumes:
      - ./client:/admin
      - /client/node_modules
    depends_on:
      - backend
