FROM node:18-alpine as builder
WORKDIR /admin

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

RUN yarn build

FROM nginx:1.21-alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /admin/dist .

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]