export const roles = {
  dashboard: ['admin', 'branch-manager', 'office-employee', 'warehouse-employee'],
  employee: ['admin', 'branch-manager'],
  branch: ['admin'],
  category: ['admin', 'branch-manager', 'office-employee'],
  subCategory: ['admin', 'branch-manager', 'office-employee'],
  farmer: ['admin', 'branch-manager', 'office-employee'],
  farmerCard: ['admin', 'branch-manager', 'office-employee'],
  product: ['admin', 'branch-manager', 'office-employee'],
  review: ['admin', 'branch-manager', 'office-employee'],
  customer: ['admin', 'branch-manager'],
  expense: ['admin', 'branch-manager'],
  salary: ['admin'],
  order: ['admin', 'branch-manager', 'warehouse-employee'],
  revenue: ['admin', 'branch-manager'],
  transaction: ['admin', 'branch-manager'],
  statisticsCount: ['admin', 'branch-manager', 'office-employee', 'warehouse-employee'],
  statisticsAmount: ['admin', 'branch-manager'],
};
